/// Bildnachweise fuer die gebuendelten Spot-Fotos (Wikimedia Commons).
/// Automatisch aus den Lizenz-Metadaten erzeugt. Alle Lizenzen erlauben die
/// kommerzielle Nutzung mit Namensnennung (CC BY / CC BY-SA / CC0 / gemeinfrei).
class PhotoCredit {
  const PhotoCredit(this.file, this.author, this.license, this.source);
  final String file;
  final String author;
  final String license;
  final String source;
}

const List<PhotoCredit> photoCredits = [
  PhotoCredit('abisko_0.jpg', 'Pavel.shyshkouski', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Aurora_in_Abisko_near_Tornetr%C3%A4sk.jpg'),
  PhotoCredit('abisko_1.jpg', 'Chad Blakley, lightsoverlapland.com', 'CC BY 3.0 de', 'https://commons.wikimedia.org/wiki/File:Aurora-abisko-fisheye.jpg'),
  PhotoCredit('abisko_2.jpg', 'Chad Blakley, lightsoverlapland.com', 'CC BY 3.0 de', 'https://commons.wikimedia.org/wiki/File:Aurora-Abisko-BlueSwirl.jpg'),
  PhotoCredit('bastei_0.jpg', 'Sir James', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:2008-07-20_Bonn-BadGodesberg_Bastei.jpg'),
  PhotoCredit('bastei_1.jpg', 'Spike', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bastei_Panorama_01.jpg'),
  PhotoCredit('bastei_2.jpg', 'John Samuel', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Rock_formations_in_Bastei_05.jpg'),
  PhotoCredit('chureito_0.jpg', 'Ximonic (Simo Räsänen)', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:View_towards_Mount_Fuji_from_Arakurayama_Sengen_Park_in_Fujiyoshida,_Yamanashi,_Japan,_2024_May_-_2.jpg'),
  PhotoCredit('chureito_1.jpg', 'Ximonic (Simo Räsänen)', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:View_towards_Mount_Fuji_from_Arakurayama_Sengen_Park_in_Fujiyoshida,_Yamanashi,_Japan,_2024_May_-_2.jpg'),
  PhotoCredit('chureito_2.jpg', '1i1ian', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Chureito_Pagoda_Snapshot.jpg'),
  PhotoCredit('eibsee_0.jpg', 'Octagon', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Eibsee_und_Ammergauer_Alpen.jpg'),
  PhotoCredit('eibsee_1.jpg', 'Octagon', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Eibsee_und_Ammergauer_Alpen.jpg'),
  PhotoCredit('eibsee_2.jpg', 'Thisik', 'CC0', 'https://commons.wikimedia.org/wiki/File:Eibsee_lake,_Alps,_Germany_08.jpg'),
  PhotoCredit('first_0.jpg', 'Roland Zumbühl', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Grindelwald_First.jpg'),
  PhotoCredit('first_1.jpg', 'W. Bulach', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:00_3403_Grindelwald-First_(Schweiz).jpg'),
  PhotoCredit('first_2.jpg', 'W. Bulach', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:00_3121._Grindelwald-First_(Schweiz).jpg'),
  PhotoCredit('glencoe_0.jpg', 'kallerna', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Campfire_and_sparks_in_Anttoora_3.jpg'),
  PhotoCredit('glencoe_1.jpg', 'Marc-Lautenbacher', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Campfire_flames_at_night.jpg'),
  PhotoCredit('glencoe_2.jpg', 'Unknown authorUnknown author', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Hunters_around_campfire_at_night,_Yukon_Territory,_ca_1900_(MEED_82).jpg'),
  PhotoCredit('hallstatt_0.jpg', 'Uoaei1', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Hallstatt_evangelische_Kirche_20180206.jpg'),
  PhotoCredit('hallstatt_1.jpg', 'C.Stadler/Bwag', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Hallstatt_-_Zentrum_.JPG'),
  PhotoCredit('hallstatt_2.jpg', 'Uoaei1', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Hallstatt_kath._Kirche_Marienaltar_Werktagsseite_01.jpg'),
  PhotoCredit('horseshoe_0.jpg', 'Charles Wang', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Horseshoe_Bend_13_February_2023.jpg'),
  PhotoCredit('horseshoe_1.jpg', 'Luca Galuzzi (Lucag)', 'CC BY-SA 2.5', 'https://commons.wikimedia.org/wiki/File:USA_10187_Horseshoe_Bend_Luca_Galuzzi_2007.jpg'),
  PhotoCredit('horseshoe_2.jpg', 'User:Moondigger', 'CC BY-SA 2.5', 'https://commons.wikimedia.org/wiki/File:Horseshoe_Bend_1_md.jpg'),
  PhotoCredit('keukenhof_0.jpg', 'Willem van Valk', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Keukenhof_tulips_-_17591061520.jpg'),
  PhotoCredit('keukenhof_1.jpg', 'Elena.laps', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Tulips_and_tree_at_Keukenhof_gardens.jpg'),
  PhotoCredit('keukenhof_2.jpg', 'Willem van Valk', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Keukenhof_tulips_-_17591061520.jpg'),
  PhotoCredit('manarola_0.jpg', 'Timothy A. Gonsalves', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Manarola_NW_Cinque_Terre_Sep23_A7C_07233.jpg'),
  PhotoCredit('manarola_1.jpg', 'Timothy A. Gonsalves', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Manarola_NW_Cemetery_Corniglia_Monterosso_Cinque_Terre_Sep23_A7C_06872.jpg'),
  PhotoCredit('manarola_2.jpg', 'Timothy A. Gonsalves', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Manarola_NW_Cinque_Terre_Sep23_A7C_07233.jpg'),
  PhotoCredit('marienbruecke_0.jpg', 'Wilfredor', 'CC0', 'https://commons.wikimedia.org/wiki/File:Neuschwanstein_Castle_2024-02.jpg'),
  PhotoCredit('marienbruecke_1.jpg', 'Ximonic, Simo Räsänen (post-processing) & Tauno Räsänen (pho', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Neuschwanstein_Castle_from_Marienbr%C3%BCcke,_2011_May.jpg'),
  PhotoCredit('marienbruecke_2.jpg', 'Thomas Wolf, www.foto-tw.de', 'CC BY-SA 3.0 de', 'https://commons.wikimedia.org/wiki/File:Schloss_Neuschwanstein_2013.jpg'),
  PhotoCredit('marinha_0.jpg', 'Mimihitam', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Praia_da_Marinha_2017.jpg'),
  PhotoCredit('marinha_1.jpg', 'Philippe Salgarolo', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Praia_de_Marinha.jpg'),
  PhotoCredit('marinha_2.jpg', 'Mimihitam', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Praia_da_Marinha_2017.jpg'),
  PhotoCredit('merzouga_0.jpg', 'Dominik Angstwurm', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Sahara_Night_Sky_(229876491).jpeg'),
  PhotoCredit('merzouga_1.jpg', 'BLMUtah', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Night_Skies_at_Little_Sahara_(49991333898).jpg'),
  PhotoCredit('merzouga_2.jpg', 'Rayane Yacine', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Bleu_Sahara_(134974669).jpeg'),
  PhotoCredit('milford_0.jpg', 'Krzysztof Golik', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Milford_Sound_in_Fiordland_National_Park_01.jpg'),
  PhotoCredit('milford_1.jpg', 'Krzysztof Golik', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Milford_Sound_in_Fiordland_National_Park_18.jpg'),
  PhotoCredit('milford_2.jpg', 'Krzysztof Golik', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Milford_Sound_in_Fiordland_National_Park_03.jpg'),
  PhotoCredit('moher_0.jpg', 'Berthold Werner', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ireland_Cliffs_of_Moher_BW_2025-09-11_14-27-51.jpg'),
  PhotoCredit('moher_1.jpg', 'Photograph Tobias Helfrich, March 27th, 2004. Modified by Pu', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Ireland_cliffs_of_moher3_Pumbaa80.jpg'),
  PhotoCredit('moher_2.jpg', 'Berthold Werner', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ireland_Cliffs_of_Moher_BW_2025-09-11_14-26-55.jpg'),
  PhotoCredit('moraine_0.jpg', 'Gorgo', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Moraine_Lake_17092005.jpg'),
  PhotoCredit('moraine_1.jpg', 'Tobias Alt, Tobi 87', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Moraine_Lake-Banff_NP.JPG'),
  PhotoCredit('moraine_2.jpg', 'Chensiyuan', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:1_moraine_lake_pano_2019.jpg'),
  PhotoCredit('oia_0.jpg', 'Giles Laurent', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:1000_Three_domes_of_Oia_in_Santorini_Photo_by_Giles_Laurent.jpg'),
  PhotoCredit('oia_1.jpg', 'Mstyslav Chernov', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Panoramic_view_of_Oia,_Santorini_island_(Thira),_Greece.jpg'),
  PhotoCredit('oia_2.jpg', 'Norbert Nagel', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:07-17-2012_-_Oia_-_Santorini_-_Greece_-_15.jpg'),
  PhotoCredit('plitvice_0.jpg', 'Someone35', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Waterfall_in_plitvice_lakes_national_park,_croatia.jpg'),
  PhotoCredit('plitvice_1.jpg', 'Sheeba Samuel', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Plitvice_Lakes_Croatia.jpg'),
  PhotoCredit('plitvice_2.jpg', 'Przemek P', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Waterfall_in_Plitvice_Lakes_National_Park.jpg'),
  PhotoCredit('pravcicka_0.jpg', 'Pudelek', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Prav%C4%8Dick%C3%A1_br%C3%A1na_(Prebischtor)_-_by_Pudelek.jpg'),
  PhotoCredit('pravcicka_1.jpg', 'Pudelek', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Prav%C4%8Dick%C3%A1_br%C3%A1na_(Prebischtor)_-_by_Pudelek.jpg'),
  PhotoCredit('pravcicka_2.jpg', 'Molgreen', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:20240317_xl_1116-Path_to_the_Prav%C4%8Dick%C3%A1_br%C3%A1na_2024_(Monoculture,_man-made_climate_change,_bark_beetle_infestation,_fire)_76.jpg'),
  PhotoCredit('preikestolen_0.jpg', 'Stefan Krause, Germany', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Preikestolen_Norge.jpg'),
  PhotoCredit('preikestolen_1.jpg', 'W. Bulach', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:00_0345_Norway_-_Preikestolen.jpg'),
  PhotoCredit('preikestolen_2.jpg', 'Andreobst', 'CC0', 'https://commons.wikimedia.org/wiki/File:Preikestolen_Felsen.jpg'),
  PhotoCredit('reine_0.jpg', 'Christoph Strässler', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Aurora_Borealis_(Northern_Light)_over_Reine,_Lofoten,_Norway.jpg'),
  PhotoCredit('reine_1.jpg', 'Christoph Strässler', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Aurora_Borealis_(Northern_Light)_over_Svolv%C3%A6r,_Lofoten,_Norway.jpg'),
  PhotoCredit('reine_2.jpg', 'Christoph Strässler', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Aurora_Borealis_(Northern_Light)_over_Reine,_Lofoten,_Norway2.jpg'),
  PhotoCredit('seceda_0.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Furnadoia_de_Seceda_y_Resciesa.JPG'),
  PhotoCredit('seceda_1.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Lift_Seceda_Gherd%C3%ABina.jpg'),
  PhotoCredit('seceda_2.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Odles_da_Seceda_da_duman_tl_nibl_Gherd%C3%ABina.jpg'),
  PhotoCredit('seiser_alm_0.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Saslonch_udu_da_Mont_de_Seuc.jpg'),
  PhotoCredit('seiser_alm_1.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Seiser_Alm_Langkofel_Pferdeschlitten.jpg'),
  PhotoCredit('seiser_alm_2.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Mont_de_S%C3%ABuc_Seiser_Alm_Montes_de_Gherd%C3%ABina.jpg'),
  PhotoCredit('skogafoss_0.jpg', 'Martin Falbisoner', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Sk%C3%B3gafoss_July_2014.JPG'),
  PhotoCredit('skogafoss_1.jpg', 'Jakub Hałun', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Sk%C3%B3gafoss_Waterfall,_Iceland,_20240720_1330_2993.jpg'),
  PhotoCredit('skogafoss_2.jpg', 'Jakub Hałun', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Sk%C3%B3gafoss_Waterfall,_Iceland,_20240720_1411_3075.jpg'),
  PhotoCredit('staubbach_0.jpg', 'Oleg Yunakov', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2025-08-22_-_Staubbach_Falls_-_02.jpg'),
  PhotoCredit('staubbach_1.jpg', 'Oleg Yunakov', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2025-08-22_-_Staubbach_Falls_-_05.jpg'),
  PhotoCredit('staubbach_2.jpg', 'Oleg Yunakov', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2025-08-22_-_Staubbach_Falls_-_02.jpg'),
  PhotoCredit('torres_0.jpg', 'Pedro Szekely from Los Angeles, USA', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Cuernos_del_Paine_in_Torres_del_Paine_National_Park.jpg'),
  PhotoCredit('torres_1.jpg', 'Martin St-Amant (S23678)', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Torres_del_Paine_-_Janvier_2010.jpg'),
  PhotoCredit('torres_2.jpg', 'Charles J. Sharp', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lesser_rhea_(Rhea_pennata_pennata)_Torres_del_Paine.jpg'),
  PhotoCredit('tre_cime_0.jpg', 'Wolfgang Moroder', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Drei_Zinnen_Tre_Cime_di_Lavaredo_Dolomites.jpg'),
  PhotoCredit('tre_cime_1.jpg', 'Ximonic (Simo Räsänen)', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Valle_della_Rienza_and_Tre_Cime_di_Lavaredo_from_Alpe_Specie,_Val_Pusteria,_Trentino-Alto_Adige,_Italy,_2025_October.jpg'),
  PhotoCredit('tre_cime_2.jpg', 'Llorenzi', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Tre_Cime_di_Lavaredo_dal_lato.JPG'),
  PhotoCredit('tunnel_view_0.jpg', 'Diliff', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Tunnel_View,_Yosemite_Valley,_Yosemite_NP_-_Diliff.jpg'),
  PhotoCredit('tunnel_view_1.jpg', 'Diliff', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Tunnel_View,_Yosemite_Valley,_Yosemite_NP_-_Diliff.jpg'),
  PhotoCredit('tunnel_view_2.jpg', 'Dllu', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Tunnel_view_at_Yosemite_dllu.jpg'),
  PhotoCredit('valensole_0.jpg', 'Unbekannt', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lavender_fields_of_Valensole,_2019.jpg'),
  PhotoCredit('valensole_1.jpg', 'Einaz80', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lavender_field_near_Valensole_2.jpg'),
  PhotoCredit('valensole_2.jpg', 'Einaz80', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Lavender_field_near_Valensole_3.jpg'),
  PhotoCredit('zugspitze_0.jpg', 'Maksym Kozlenko', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2019-08-01_Zugspitze_8.jpg'),
  PhotoCredit('zugspitze_1.jpg', 'Maksym Kozlenko', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2019-08-01_Zugspitze_8.jpg'),
  PhotoCredit('zugspitze_2.jpg', 'Maksym Kozlenko', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2019-08-01_Zugspitze_7.jpg'),
];
